aws_region       = "us-east-1"
environment      = "prod"
vpc_cidr         = "10.2.0.0/16"
vpc_name         = "production-vpc"
subnet_cidr      = "10.2.1.0/24"
availability_zone = "us-east-1c"
instance_type    = "t2.small"
ami_id           = "ami-02dfbd4ff395f2a1b"  # Ubuntu 22.04 LTS
instance_name    = "webserver"
